import { headers } from "next/headers";
import { NegotiationDemo } from "../components/negotiation-demo";

export const dynamic = "force-dynamic";

export default async function Page() {
  // A per-request render lets Next.js attach the CSP nonce generated by
  // middleware to every framework script.  Static HTML cannot carry that
  // request-specific nonce safely.
  await headers();
  return <NegotiationDemo />;
}
